services:
  redmine-tunnel:
    container_name: redmine-tunnel
    image: alpine:latest
    command: >
      sh -c "apk add --no-cache openssh && 
             ssh -v -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa ubuntu@staging.forecasting-v2.gluzdov.com -N -L 0.0.0.0:3306:redmine-pr-rds-db-read.c1kaki1qbk4o.us-east-1.rds.amazonaws.com:3306"
    volumes:
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      - SSH_KEY=/root/.ssh/id_rsa